### ISSUE TITLE
sqlalchemy.exc.OperationalError when connecting to the site

### ISSUE THREAD

**Issue by sagarverma** [granularai/geometa#11]
```sqlalchemy.exc.OperationalError
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: areas_of_interest
[SQL: SELECT areas_of_interest.id AS areas_of_interest_id, areas_of_interest.name AS areas_of_interest_name, areas_of_interest.location AS areas_of_interest_location, areas_of_interest.aoi_ref AS areas_of_interest_aoi_ref, areas_of_interest.change_type AS areas_of_interest_change_type, areas_of_interest.neighborhood_type AS areas_of_interest_neighborhood_type, areas_of_interest.geographic_type AS areas_of_interest_geographic_type, areas_of_interest.created_at AS areas_of_interest_created_at, areas_of_interest.user_id AS areas_of_interest_user_id, count(areas_of_interest.user_id) AS count_1 
FROM areas_of_interest GROUP BY areas_of_interest.user_id, areas_of_interest.id]
(Background on this error at: http://sqlalche.me/e/e3q8)

Traceback (most recent call last)
File "/home/sagar/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
self.dialect.do_execute(
File "/home/sagar/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
cursor.execute(statement, parameters)
The above exception was the direct cause of the following exception:
File "/home/sagar/.local/lib/python3.8/site-packages/flask/app.py", line 2463, in __call__
return self.wsgi_app(environ, start_response)
File "/home/sagar/.local/lib/python3.8/site-packages/flask/app.py", line 2449, in wsgi_app
response = self.handle_exception(e)
File "/home/sagar/.local/lib/python3.8/site-packages/flask/app.py", line 1866, in handle_exception
reraise(exc_type, exc_value, tb)
File "/home/sagar/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/home/sagar/.local/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
response = self.full_dispatch_request()
File "/home/sagar/.local/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/sagar/.local/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/home/sagar/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/home/sagar/.local/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
rv = self.dispatch_request()
File "/home/sagar/.local/lib/python3.8/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
return view_func(**req.view_args)
File "/app/geometa/public/views.py", line 47, in home
users=AOI.query.with_entities(AOI, func.count(AOI.user_id)).group_by(AOI.user_id, AOI.id).all())
File "/home/sagar/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3233, in all
return list(self)
File "/home/sagar/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3389, in __iter__
return self._execute_and_instances(context)
File "/home/sagar/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3414, in _execute_and_instances
result = conn.execute(querycontext.statement, self._params)
File "/home/sagar/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 982, in execute
return meth(self, multiparams, params)
File "/home/sagar/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
return connection._execute_clauseelement(self, multiparams, params)
File "/home/sagar/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1095, in _execute_clauseelement
ret = self._execute_context(
File "/home/sagar/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
self._handle_dbapi_exception(
File "/home/sagar/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
util.raise_from_cause(sqlalchemy_exception, exc_info)
File "/home/sagar/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
reraise(type(exception), exception, tb=exc_tb, cause=cause)
File "/home/sagar/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
raise value.with_traceback(tb)
File "/home/sagar/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
self.dialect.do_execute(
File "/home/sagar/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: areas_of_interest
[SQL: SELECT areas_of_interest.id AS areas_of_interest_id, areas_of_interest.name AS areas_of_interest_name, areas_of_interest.location AS areas_of_interest_location, areas_of_interest.aoi_ref AS areas_of_interest_aoi_ref, areas_of_interest.change_type AS areas_of_interest_change_type, areas_of_interest.neighborhood_type AS areas_of_interest_neighborhood_type, areas_of_interest.geographic_type AS areas_of_interest_geographic_type, areas_of_interest.created_at AS areas_of_interest_created_at, areas_of_interest.user_id AS areas_of_interest_user_id, count(areas_of_interest.user_id) AS count_1
FROM areas_of_interest GROUP BY areas_of_interest.user_id, areas_of_interest.id]
(Background on this error at: http://sqlalche.me/e/e3q8)
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.```

**Comment by sagarverma** [comment]
Resolved by @siddygups.
